### ISSUE TITLE
Connecting Odin with Mininet-Wifi

### ISSUE THREAD

**Issue by uhlik1889** [Wi5/odin-wi5-controller#11]
Hi,

I have controller connected via loopback 127.0.0.1:6653, to the Mininet. The clients are at 10.0.0.x/8 subnet. The interfaces has been created and the start.sh script runs fine, but I have no new log messages in the controller.

How is the configuration of the floodlightdefault.properties and poolfile, have to be set in my case.

I have them so far like this.
# start.sh:
#Variables
"Setting variables"
CTLIP=127.0.0.1     # Controller IP address
SW=br0              # Name of the bridge
DPPORTS="ap1-wlan1"    # Port for data plane
VSCTL="ovs-vsctl"   # Command to be used to invoke openvswitch

#OVS
#"Restarting OpenvSwitch"
/etc/init.d/openvswitch-switch stop
sleep 1
##The next line is added in order to start the controller after stopping openvswitch
read -p "Now you can launch the Wi-5 odin controller and press Enter" pause

##Clean the OpenVSwitch database
if [ -d "/etc/openvswitch" ]; then
 #"OpenVSwitch folder already exists"
else
 #"OpenVSwitch folder created"
  mkdir /etc/openvswitch
fi
if [ -f "/etc/openvswitch/conf.db" ]; then
  #"Cleaning OpenVSwitch database"
  rm /etc/openvswitch/conf.db
fi
if [ -f "/var/run/db.sock" ]; then
  rm /var/run/db.sock
fi
if [ -f "/var/run/ovsdb-server.pid" ]; then
  rm /var/run/ovsdb-server.pid
fi
if [ -f "/var/run/ovs-vswitchd.pid" ]; then
  rm /var/run/ovs-vswitchd.pid
fi

##Launch OpenVSwitch
#"Launching OpenVSwitch"
/etc/init.d/openvswitch-switch start

##Create the bridge
$VSCTL add-br $SW
ifconfig $SW up ## In OpenWrt 15.05 the bridge is created down

##Configure the OpenFlow Controller  ---------------6653-controller-port-----------------
$VSCTL set-controller $SW tcp:$CTLIP:6653

#Add the data plane ports to OpenVSwitch
for i in $DPPORTS ; do
  PORT=$i
  ifconfig $PORT up
  $VSCTL add-port $SW $PORT
done

#Add the 'ap' interface to OpenVSwitch
#"Adding Click interface 'ap' to OVS"
ifconfig ap up            ## Putting the interface 'ap' up
$VSCTL add-port $SW ap    ## Adding 'ap' interface (click Interface) to OVS
sleep 1

#Launch click
sleep 3
echo "Launching Click"

## Poolfile:
I haven't changed this one. 

## Floodlightdefault.properties:
`floodlight.modules = net.floodlightcontroller.storage.memory.MemoryStorageSource,\
net.floodlightcontroller.staticflowentry.StaticFlowEntryPusher,\
net.floodlightcontroller.learningswitch.LearningSwitch,\
net.floodlightcontroller.jython.JythonDebugInterface,\
net.floodlightcontroller.counter.CounterStore,\
net.floodlightcontroller.perfmon.PktInProcessingTime,\
net.floodlightcontroller.ui.web.StaticWebRoutable, \
net.floodlightcontroller.odin.master.OdinMaster
net.floodlightcontroller.restserver.RestApiServer.port = 8080
net.floodlightcontroller.core.FloodlightProvider.openflowport = 6653
net.floodlightcontroller.jython.JythonDebugInterface.port = 6655
net.floodlightcontroller.odin.master.OdinMaster.masterPort = 6653
net.floodlightcontroller.odin.master.OdinMaster.poolFile = poolfile
net.floodlightcontroller.odin.master.OdinMaster.clientList = odin_client_list`

**Comment by josemariasaldana** [comment]
I assume you have to specify the IP addresses of the Access Points at the beginning of poolfile:
https://github.com/Wi5/odin-wi5-controller/blob/master/poolfile

After `NODES` you have to put the list with the IPs of the APs.

```
# Pool-1
NAME pool-1
NODES 192.168.1.13 192.168.1.14 192.168.1.15
NETWORKS wi5-demo
```

**Comment by uhlik1889** [comment]
All this is done. The problem was in version of controller. It was showing some error message, which I was ignoring. Simple downloading it again, and replacing, fix the issue.
