### ISSUE TITLE
About LVAP

### ISSUE THREAD

**Issue by CanRui-Wu** [Wi5/odin-wi5-controller#2]
Hi.
I think that one LVAP should serve for one STA.
But It seem that one LVAP can be associated by two STAs.
And when one LVAP serve for two or more STA. I use iperf to test, only one STA can communicate with the Odin Agent.
![Uploading Screenshot from 2017-05-11 20:00:55.png…]()
Please give me some help. THX.

**Comment by josemariasaldana** [comment]
The idea is that one LVAP can only serve one STA. This is the basis of Odin. In fact, the LVAP is built using part of the MAC of the STA.

The system is described in the following Masters' thesis:
http://lalithsuresh.files.wordpress.com/2011/04/lalith-thesis.pdf

You may find some information in this article:
https://www.usenix.org/system/files/conference/atc14/atc14-paper-schulz_zander.pdf

And this is a presentation:
https://www.usenix.org/conference/atc14/technical-sessions/presentation/schulz-zandery
