### ISSUE TITLE
More info about Statistics.java please

### ISSUE THREAD

**Issue by peterrz** [Wi5/odin-wi5-controller#3]
this class, which shows the collected statistics (https://github.com/Wi5/odin-wi5-controller/blob/Development/src/main/java/net/floodlightcontroller/odin/applications/ShowStatistics.java)
how actually does it work ?, Any REST API available for this? 
thanks to you.

**Comment by josemariasaldana** [comment]
This is a simple application, which is able to show by the Controller's screen, the statistics that have been gathered by the Agents.

You have all the information here: http://www.wi5.eu/wp-content/uploads/2015/02/D3_1-Definition-of-the-performance-monitoring-mechanisms.pdf. It is a deliverable of the Wi-5 project. See sections 3.3.1 and 3.3.2.
