### ISSUE TITLE
Add the IP address of the detection agent in the poolfile

### ISSUE THREAD

**Issue by josemariasaldana** [Wi5/odin-wi5-controller#4]
Currently, the IP address of the [detection agent(s)](https://github.com/Wi5/odin-wi5-flow-detection) has to be written directly in the Java code of [`OdinAgent.java`](https://github.com/Wi5/odin-wi5-controller/blob/integrate_detection/src/main/java/net/floodlightcontroller/odin/master/OdinAgent.java), using the variable `String detectionAgentIP`.

This could be fixed so that the IP address of the detection agent could be specified in the [`poolfile`](https://github.com/Wi5/odin-wi5-controller/blob/master/poolfile).

**Comment by rubenmunilla** [comment]
Now we can add a section in the [`poolfile`](https://github.com/Wi5/odin-wi5-controller/blob/master/poolfile) called DETECTION, where there will be the ip address assigned to the detector.

If no detector is been used, it is not necessary to add the section, the controller itself selects 0.0.0.0 as detector IP and there is no conflict with possible stations.

Changes has been made in [`OdinMaster.java`](https://github.com/Wi5/odin-wi5-controller/blob/integrate_detection/src/main/java/net/floodlightcontroller/odin/master/OdinMaster.java) and [`OdinAgent.java`](https://github.com/Wi5/odin-wi5-controller/blob/integrate_detection/src/main/java/net/floodlightcontroller/odin/master/OdinAgent.java).
