### ISSUE TITLE
Fix problem with the logs of ShowMatrixOfDistancedBs.java

### ISSUE THREAD

**Issue by josemariasaldana** [Wi5/odin-wi5-controller#9]
In some cases, in https://github.com/Wi5/odin-wi5-controller/blob/Development/src/main/java/net/floodlightcontroller/odin/applications/ShowMatrixOfDistancedBs.java, the log calls say 

`System.out.println("[ShowScannedStationsStatistics]`

instead of

`System.out.println("[ShowMatrixOfDistancedBs] `

**Comment by rubenmunilla** [comment]
Fixed, and improvement done, now matrix is printed after the scan.
